### ISSUE TITLE
I don't think we should ask for the gender

### ISSUE THREAD

**Issue by bast** [coderefinery/workshop-administration#1]
It should not matter, it does not matter to me, does not matter to us. Let me know what you think.

**Comment by wikfeldt** [comment]
it doesn't matter to me either, but it's still a question that sheds some light on progress in diversification. And it often does get asked in registration forms, especially in areas like computer science and software engineering. So it by no means looks weird or surprising to people i think, but the question is whether we'd like to keep an eye on diversification (and perhaps try different outreach strategies and see if it improves the gender balance), or whether we should just ignore it

**Comment by bast** [comment]
Good point. The data is still interesting. I just hope that nobody is hurt/offended by the question. But since we clarify why we ask it and also give the option to not indicate, it is possibly fine and we can leave it there.

**Comment by wikfeldt** [comment]
i'm not sure how many see it in the same way, but i've come to see such questions as indications that the organizers of whatever thing i'm registering for care about diversification, so it even gives a slightly positive impression! 
At least i don't think that anyone finds it offending

**Comment by bast** [comment]
That's very good. Thanks for feedback! Let's keep it then.
